// SPDX-License-Identifier: Apache-2.0
package runtime

import (
	"bytes"
	"context"
	"encoding/json"
	"strings"

	"github.com/STAR-Ability/code-startrack-judge/internal/packages"
)

// StatementArtifactEvidence contains structural evidence only. Original filenames,
// generated bytes and tool diagnostics remain in the private qualification run.
type StatementArtifactEvidence struct {
	Kind           string `json:"kind"`
	ManifestSHA256 string `json:"manifestSha256"`
	FileCount      int    `json:"fileCount"`
	FileBytes      int64  `json:"fileBytes"`
	PrimarySHA256  string `json:"primarySha256"`
	PrimaryBytes   int64  `json:"primaryBytes"`
	MathElements   int    `json:"mathElements"`
}

type StatementQualification struct {
	Artifacts           []StatementArtifactEvidence `json:"artifacts"`
	Workspaces          []StatementWorkspaceFacts   `json:"workspaces"`
	ParentProcessDenied bool                        `json:"parentProcessDenied"`
	RawLog              []byte                      `json:"-"`
}

type StatementWorkspaceFacts struct {
	TransportBytes         int64  `json:"transportBytes"`
	RegularBytes           int64  `json:"regularBytes"`
	RegularFiles           int    `json:"regularFiles"`
	TotalBytes             uint64 `json:"totalBytes"`
	TotalInodes            uint64 `json:"totalInodes"`
	PeakObservedUsedBytes  uint64 `json:"peakObservedUsedBytes"`
	PeakObservedUsedInodes uint64 `json:"peakObservedUsedInodes"`
}

func (StatementQualification) String() string {
	return "private statement qualification [diagnostics redacted]"
}
func (q StatementQualification) GoString() string { return q.String() }

// QualifyStatement is an offline qualification operation, absent from the
// scheduler/API protocol. It uses the same finite public-role transport and
// isolation profile as mature verification, but asks the original converter to
// retain its sanitized PDF and original HTML for structural artifact evidence.
func (a *Adapter) QualifyStatement(ctx context.Context, m packages.Manifest) (out StatementQualification, err error) {
	if packages.ValidateManifest(m) != nil {
		return out, failure("FROZEN_MANIFEST_INVALID", false)
	}
	if !a.Snapshot(ctx).MatureReady {
		return out, failure("RUNTIME_NOT_READY", false)
	}
	files, e := a.matureStatementFiles(ctx, m)
	if e != nil {
		return out, e
	}
	var transportBytes int64
	for _, raw := range files {
		transportBytes += int64(len(raw))
	}
	public := map[string]int64{m.Statement.ValidationView.Path: m.Statement.ValidationView.SizeBytes}
	for _, f := range m.Files {
		if f.Role == "OTHER" && strings.HasPrefix(f.NormalizedPath, "problem_statement/") || f.NormalizedPath == "problem.yaml" {
			public[f.NormalizedPath] = f.NormalizedSizeBytes
		}
	}
	for _, c := range m.Tests {
		if c.Visibility == "SAMPLE" {
			public[c.Input.Path], public[c.Answer.Path] = c.Input.SizeBytes, c.Answer.SizeBytes
		}
	}
	var regularBytes int64
	for _, size := range public {
		regularBytes += size
	}
	bridge, e := a.bridgeBytes(ctx)
	if e != nil {
		return out, e
	}
	files["problemtools-bridge.py"] = bridge
	for _, kind := range []string{"pdf", "html"} {
		response, e := a.matureRunBytes(ctx, "statement-qualification/"+kind,
			[]string{"/usr/local/bin/python3", "-I", "/w/problemtools-bridge.py", "--qualify-statement", kind},
			nil, files, statementLimits())
		if private, logErr := decodeMatureBytes(response.StderrBase64, 8<<20); logErr == nil {
			remaining := (2 << 20) - len(out.RawLog)
			if len(private) > remaining {
				private = private[:remaining]
			}
			out.RawLog = append(out.RawLog, private...)
		}
		if e != nil {
			return out, e
		}
		raw, e := decodeMatureBytes(response.StdoutBase64, 65536)
		if e != nil {
			return out, e
		}
		artifact, workspace, e := statementQualificationReport(raw, strings.ToUpper(kind))
		if e != nil || response.WaitStatus != 0 {
			return out, failure("STATEMENT_QUALIFICATION_FAILED", false)
		}
		if workspace.TransportBytes != transportBytes || workspace.RegularBytes != regularBytes || workspace.RegularFiles != len(public) {
			return out, failure("STATEMENT_TRANSPORT_MEASUREMENT_INVALID", false)
		}
		out.Artifacts = append(out.Artifacts, artifact)
		out.Workspaces = append(out.Workspaces, workspace)
	}
	out.ParentProcessDenied = true
	return out, nil
}

func statementQualificationReport(raw []byte, kind string) (StatementArtifactEvidence, StatementWorkspaceFacts, error) {
	invalid := func() (StatementArtifactEvidence, StatementWorkspaceFacts, error) {
		return StatementArtifactEvidence{}, StatementWorkspaceFacts{}, failure("STATEMENT_QUALIFICATION_REPORT_INVALID", false)
	}
	var fields map[string]json.RawMessage
	if len(raw) > 65536 || strictDecode(raw, &fields) != nil || len(fields) != 6 {
		return invalid()
	}
	for _, name := range []string{"ok", "errors", "warnings", "artifacts", "parentProcessDenied", "workspace"} {
		if fields[name] == nil || bytes.Equal(bytes.TrimSpace(fields[name]), []byte("null")) {
			return invalid()
		}
	}
	var workspace StatementWorkspaceFacts
	if strictDecode(fields["workspace"], &workspace) != nil {
		return invalid()
	}
	var workspaceFields map[string]json.RawMessage
	if json.Unmarshal(fields["workspace"], &workspaceFields) != nil || len(workspaceFields) != 7 {
		return invalid()
	}
	for _, name := range []string{"transportBytes", "regularBytes", "regularFiles", "totalBytes", "totalInodes", "peakObservedUsedBytes", "peakObservedUsedInodes"} {
		if workspaceFields[name] == nil || bytes.Equal(bytes.TrimSpace(workspaceFields[name]), []byte("null")) {
			return invalid()
		}
	}
	if workspace.TransportBytes < 1024 || workspace.TransportBytes > 768<<20 || workspace.RegularBytes < 1 || workspace.RegularBytes > 512<<20 || workspace.RegularFiles < 2 || workspace.RegularFiles > 65536 || workspace.TotalBytes != 2<<30 || workspace.TotalInodes != 262144 || workspace.PeakObservedUsedBytes > workspace.TotalBytes || workspace.PeakObservedUsedBytes < uint64(workspace.TransportBytes+workspace.RegularBytes) || workspace.PeakObservedUsedInodes > workspace.TotalInodes || workspace.PeakObservedUsedInodes < uint64(workspace.RegularFiles) {
		return invalid()
	}
	delete(fields, "workspace")
	artifactRaw, e := json.Marshal(fields)
	if e != nil {
		return invalid()
	}
	artifact, e := statementArtifactReport(artifactRaw, kind)
	if e != nil {
		return invalid()
	}
	return artifact, workspace, nil
}

func statementArtifactReport(raw []byte, kind string) (StatementArtifactEvidence, error) {
	var report struct {
		OK                  bool                       `json:"ok"`
		Errors              int                        `json:"errors"`
		Warnings            int                        `json:"warnings"`
		Artifacts           *StatementArtifactEvidence `json:"artifacts"`
		ParentProcessDenied bool                       `json:"parentProcessDenied"`
	}
	invalid := func() (StatementArtifactEvidence, error) {
		return StatementArtifactEvidence{}, failure("STATEMENT_ARTIFACT_REPORT_INVALID", false)
	}
	if len(raw) > 65536 || strictDecode(bytes.TrimSpace(raw), &report) != nil || !report.OK || !report.ParentProcessDenied || report.Errors != 0 || report.Warnings < 0 || report.Warnings > 1000000 || report.Artifacts == nil {
		return invalid()
	}
	var fields map[string]json.RawMessage
	if json.Unmarshal(raw, &fields) != nil || len(fields) != 5 {
		return invalid()
	}
	for _, name := range []string{"ok", "errors", "warnings", "artifacts", "parentProcessDenied"} {
		if fields[name] == nil || bytes.Equal(bytes.TrimSpace(fields[name]), []byte("null")) {
			return invalid()
		}
	}
	var artifactFields map[string]json.RawMessage
	if json.Unmarshal(fields["artifacts"], &artifactFields) != nil || len(artifactFields) != 7 {
		return invalid()
	}
	for _, name := range []string{"kind", "manifestSha256", "fileCount", "fileBytes", "primarySha256", "primaryBytes", "mathElements"} {
		if artifactFields[name] == nil || bytes.Equal(bytes.TrimSpace(artifactFields[name]), []byte("null")) {
			return invalid()
		}
	}
	a := *report.Artifacts
	if kind != "PDF" && kind != "HTML" || a.Kind != kind || !digestPattern.MatchString(a.ManifestSHA256) || !digestPattern.MatchString(a.PrimarySHA256) || a.FileCount < 1 || a.FileCount > 4096 || a.FileBytes < 1 || a.FileBytes > 256<<20 || a.PrimaryBytes < 1 || a.PrimaryBytes > 64<<20 || a.PrimaryBytes > a.FileBytes || a.MathElements < 0 || a.MathElements > 1000000 || kind == "PDF" && a.MathElements != 0 {
		return invalid()
	}
	return a, nil
}
