// Package restclient implements the private REST transport of the pinned
// go-judge runtime. It exposes no HTTP handlers or caller execution templates.
package restclient

import (
	"fmt"
	"math"
	"path"
	"strings"
	"unicode"
	"unicode/utf8"
)

const Endpoint = "http://127.0.0.1:5050"

// FileID is the eight-character base32 identifier generated by pinned go-judge.
// It is an opaque cache identity, never a caller filesystem path or URL.
type FileID string

func (id FileID) valid() bool {
	if len(id) != 8 {
		return false
	}
	for _, c := range id {
		if !(c >= 'A' && c <= 'Z' || c >= '2' && c <= '7') {
			return false
		}
	}
	return true
}

// File supplies a cached input or a bounded output collector. Exactly one
// variant is required. Byte inputs must first be uploaded; inline JSON strings,
// local-host paths, symlinks, streams and TTY descriptors are unsupported.
type File struct {
	ID          FileID
	Collector   string
	LimitBytes  int64
	CollectPipe bool
}

type Output struct {
	Name     string
	Optional bool
}

// Command is built exclusively by reviewed service-owned execution profiles.
// All limits are frozen by the orchestrator; duration fields are nanoseconds
// and size fields bytes. This transport does not select profiles or verdicts.
type Command struct {
	Args              []string
	Env               []string
	Files             []File
	CopyIn            map[string]FileID
	CopyOutCached     []Output
	CPULimitNS        uint64
	ClockLimitNS      uint64
	MemoryLimitBytes  uint64
	StackLimitBytes   uint64
	ProcessLimit      uint64
	CopyOutMaxBytes   uint64
	StrictMemoryLimit bool
	DataSegmentLimit  bool
	AddressSpaceLimit bool
}

type Request struct {
	RequestID string
	Commands  []Command
}

// Status preserves the pinned runtime status, including infrastructure errors.
// A compiler exit, contestant exit and checker exit have different meanings;
// verdict classification belongs to the role-aware execution adapter.
type Status string

const (
	Invalid            Status = "Invalid"
	Accepted           Status = "Accepted"
	WrongAnswer        Status = "Wrong Answer"
	PartiallyCorrect   Status = "Partially Correct"
	MemoryLimit        Status = "Memory Limit Exceeded"
	TimeLimit          Status = "Time Limit Exceeded"
	OutputLimit        Status = "Output Limit Exceeded"
	FileError          Status = "File Error"
	NonzeroExit        Status = "Nonzero Exit Status"
	Signalled          Status = "Signalled"
	DangerousSyscall   Status = "Dangerous Syscall"
	JudgementFailed    Status = "Judgement Failed"
	InvalidInteraction Status = "Invalid Interaction"
	InternalError      Status = "Internal Error"
)

func (s Status) valid() bool {
	switch s {
	case Invalid, Accepted, WrongAnswer, PartiallyCorrect, MemoryLimit, TimeLimit,
		OutputLimit, FileError, NonzeroExit, Signalled, DangerousSyscall,
		JudgementFailed, InvalidInteraction, InternalError:
		return true
	}
	return false
}

// FileErrorType preserves only a bounded pinned structural enum, never the
// failed path or raw diagnostic. Role-aware adapters may distinguish resource
// caps from infrastructure file-operation failures without parsing messages.
type FileErrorType string

const (
	CopyInOpenFile        FileErrorType = "CopyInOpenFile"
	CopyInCreateDir       FileErrorType = "CopyInCreateDir"
	CopyInCreateFile      FileErrorType = "CopyInCreateFile"
	CopyInCopyContent     FileErrorType = "CopyInCopyContent"
	CopyOutOpen           FileErrorType = "CopyOutOpen"
	CopyOutNotRegularFile FileErrorType = "CopyOutNotRegularFile"
	CopyOutSizeExceeded   FileErrorType = "CopyOutSizeExceeded"
	CopyOutCreateFile     FileErrorType = "CopyOutCreateFile"
	CopyOutCopyContent    FileErrorType = "CopyOutCopyContent"
	CollectSizeExceeded   FileErrorType = "CollectSizeExceeded"
	Symlink               FileErrorType = "Symlink"
)

func (t FileErrorType) valid() bool {
	switch t {
	case CopyInOpenFile, CopyInCreateDir, CopyInCreateFile, CopyInCopyContent,
		CopyOutOpen, CopyOutNotRegularFile, CopyOutSizeExceeded, CopyOutCreateFile,
		CopyOutCopyContent, CollectSizeExceeded, Symlink:
		return true
	}
	return false
}

// Result retains exact numeric measurements and opaque cached-output identities.
// Raw upstream errors, file paths, tool diagnostics and inline output are never
// retained in this projection. Cached byte content requires an explicit download.
type Result struct {
	Status         Status
	ExitStatus     int
	CPUTimeNS      uint64
	WallTimeNS     uint64
	MemoryBytes    uint64
	ProcessPeak    uint64
	CachedFiles    map[string]FileID
	HasError       bool
	FileErrorCount int
	FileErrorTypes []FileErrorType
}

func (r Result) String() string {
	return fmt.Sprintf("sandbox result [status=%s exit=%d cached=%d]", r.Status, r.ExitStatus, len(r.CachedFiles))
}
func (r Result) GoString() string { return r.String() }

type ErrorKind string

const (
	ConfigurationError  ErrorKind = "configuration"
	RequestError        ErrorKind = "request"
	BoundsError         ErrorKind = "bounds"
	TransportError      ErrorKind = "transport"
	AuthenticationError ErrorKind = "authentication"
	MissingFileError    ErrorKind = "missing_file"
	RejectedError       ErrorKind = "rejected"
	UnavailableError    ErrorKind = "unavailable"
	RedirectError       ErrorKind = "redirect"
	ProtocolError       ErrorKind = "protocol"
	CleanupError        ErrorKind = "cleanup"
)

// Error contains bounded structural diagnostics only. It never wraps upstream
// messages, response bodies, URLs supplied by a server, or credential values.
type Error struct {
	Kind          ErrorKind
	HTTPStatus    int
	Retryable     bool
	CleanupFailed bool
}

func (e *Error) Error() string { return "sandbox REST " + string(e.Kind) + " failure" }

// Limits are deployment-owned transport bounds, not submission DTO fields.
// Zero fields use defaults; larger-than-hard-ceiling configurations are rejected.
type Limits struct {
	FileBytes     int64
	RequestBytes  int64
	ResponseBytes int64
	Commands      int
	Files         int
}

func normalizeLimits(l Limits) (Limits, error) {
	defaults := Limits{FileBytes: 64 << 20, RequestBytes: 2 << 20, ResponseBytes: 1 << 20, Commands: 8, Files: 256}
	if l.FileBytes == 0 {
		l.FileBytes = defaults.FileBytes
	}
	if l.RequestBytes == 0 {
		l.RequestBytes = defaults.RequestBytes
	}
	if l.ResponseBytes == 0 {
		l.ResponseBytes = defaults.ResponseBytes
	}
	if l.Commands == 0 {
		l.Commands = defaults.Commands
	}
	if l.Files == 0 {
		l.Files = defaults.Files
	}
	if l.FileBytes < 1 || l.FileBytes > defaults.FileBytes || l.RequestBytes < 1 || l.RequestBytes > defaults.RequestBytes || l.ResponseBytes < 1 || l.ResponseBytes > defaults.ResponseBytes || l.Commands < 1 || l.Commands > defaults.Commands || l.Files < 1 || l.Files > defaults.Files {
		return Limits{}, &Error{Kind: ConfigurationError}
	}
	return l, nil
}

func validText(s string, max int) bool {
	return len(s) <= max && utf8.ValidString(s) && !strings.ContainsRune(s, '\x00')
}

func validName(s string) bool {
	if len(s) == 0 || !validText(s, 512) || path.Clean(s) != s || path.IsAbs(s) || s == "." || strings.ContainsAny(s, "\\:?%") || strings.IndexFunc(s, unicode.IsControl) >= 0 {
		return false
	}
	for _, part := range strings.Split(s, "/") {
		if part == ".." || part == "." {
			return false
		}
	}
	return true
}

func validateFile(f File, limits Limits) bool {
	if f.ID != "" {
		return f.ID.valid() && f.Collector == "" && f.LimitBytes == 0 && !f.CollectPipe
	}
	return validName(f.Collector) && f.LimitBytes > 0 && f.LimitBytes <= limits.FileBytes
}

func validEnvironment(entry string) bool {
	key, _, found := strings.Cut(entry, "=")
	if !found || !validText(entry, 4096) {
		return false
	}
	// No service tokens, DB/storage credentials or inherited environment entries.
	switch key {
	case "PATH", "LANG", "LC_ALL", "HOME", "TMPDIR":
		return true
	}
	return false
}

func validateRequest(r Request, limits Limits) error {
	if r.RequestID == "" || !validText(r.RequestID, 128) || strings.IndexFunc(r.RequestID, unicode.IsControl) >= 0 || len(r.Commands) < 1 || len(r.Commands) > limits.Commands {
		return &Error{Kind: RequestError}
	}
	totalFiles := 0
	for _, c := range r.Commands {
		if len(c.Args) < 1 || len(c.Args) > 256 || !path.IsAbs(c.Args[0]) || !validName(strings.TrimPrefix(c.Args[0], "/")) || len(c.Env) > 5 || len(c.Files) != 3 || c.CPULimitNS == 0 || c.CPULimitNS > math.MaxInt64 || c.ClockLimitNS < c.CPULimitNS || c.ClockLimitNS > math.MaxInt64 || c.MemoryLimitBytes == 0 || c.MemoryLimitBytes > math.MaxInt64 || c.StackLimitBytes > c.MemoryLimitBytes || c.ProcessLimit == 0 || c.ProcessLimit > 4096 || c.CopyOutMaxBytes == 0 || c.CopyOutMaxBytes > uint64(limits.FileBytes) {
			return &Error{Kind: RequestError}
		}
		for _, arg := range c.Args {
			if !validText(arg, 8192) {
				return &Error{Kind: RequestError}
			}
		}
		envNames := make(map[string]bool)
		for _, entry := range c.Env {
			key, _, _ := strings.Cut(entry, "=")
			if !validEnvironment(entry) || envNames[key] {
				return &Error{Kind: RequestError}
			}
			envNames[key] = true
		}
		for name, id := range c.CopyIn {
			if !validName(name) || !id.valid() {
				return &Error{Kind: RequestError}
			}
		}
		outputNames := make(map[string]bool)
		for _, output := range c.CopyOutCached {
			if !validName(output.Name) || outputNames[output.Name] {
				return &Error{Kind: RequestError}
			}
			outputNames[output.Name] = true
		}
		collectors := make(map[string]bool)
		for i, file := range c.Files {
			if !validateFile(file, limits) {
				return &Error{Kind: RequestError}
			}
			// Owned execution profiles use cached stdin and bounded stdout/stderr
			// collectors. Each collector must use the binary cache output route.
			if i == 0 {
				if file.ID == "" {
					return &Error{Kind: RequestError}
				}
				continue
			}
			if file.ID != "" || !outputNames[file.Collector] || collectors[file.Collector] {
				return &Error{Kind: RequestError}
			}
			collectors[file.Collector] = true
		}
		totalFiles += len(c.Files) + len(c.CopyIn) + len(c.CopyOutCached)
		if totalFiles > limits.Files {
			return &Error{Kind: BoundsError}
		}
	}
	return nil
}
